name: Setup Node.js and pnpm
description: Setup Node.js, pnpm, and install dependencies with caching

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '24'
  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: '10.28.1'
  install-dependencies:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'
  setup-cache:
    description: 'Whether to setup pnpm cache'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: Get pnpm store directory
      if: inputs.setup-cache == 'true'
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      if: inputs.setup-cache == 'true'
      uses: actions/cache@v5
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: pnpm install --frozen-lockfile
